### ISSUE TITLE
UTF8 support (Issue: utf8 encoded content is translated to latin-1)

### ISSUE THREAD

**Issue by 00dingens** [bitwalker/conform#98]
*Issue*: UTF8 characters in config files are not supported / handled properly.

*Code*: The code at https://github.com/bitwalker/conform/blob/master/src/conform_parse.erl#L155 converts utf8 encoded content explicitly to latin1.

*Effect*: So if we have e.g. a value like "ú..." (U+00FA) in the config file the output will be <<250,...>> which is no valid utf8 content. (the correct output would be <<195, 186,...>>)

*Question 1*: Why? Is there a problem with leaving content encoded as it is?

*Question 2*: Can the code please be updated / fixed to support utf8 encoded config files?

**Comment by bitwalker** [comment]
I've pushed the fix to master, mind giving it a shot?

**Comment by 00dingens** [comment]
Way better.
To get it working I need a little fix.
See my MR: https://github.com/bitwalker/conform/pull/99

**Comment by 00dingens** [comment]
One test fails - but since this test only shows that utf8 is not supported: maybe it should be changed to assert the current output.

**Comment by bitwalker** [comment]
Done

**Comment by 00dingens** [comment]
seems that this issue is not solved completely. on `mix conform.effective` everything is fine, but in a release  the latin-1 content somehow still remains.
